### ISSUE TITLE
Data splitting: check-up

### ISSUE THREAD

**Issue by rkdarst** [CxAalto/koota-ios#1]
- Already done
- Close this issue once it has been verified to work properly.

**Comment by rkdarst** [comment]
- Re-check data splitting
- Packets should be <1MB, a few hundred KB is ideal.  When splitting data, I split anything larger than 1MB to 1000 rows/packet.
- What about the two byte packets?

**Comment by arashbm** [comment]
Two byte packets should no longer be an issue (a check to see if number of rows > 0 does the trick).
