### ISSUE TITLE
Aware iOS investigation

### ISSUE THREAD

**Issue by rkdarst** [CxAalto/koota-ios#13]
- [ ] Become generally familiar with the app code
- [ ] Investigate deploygate.  Make a report on how it works.
  - [ ] how many devices can it be deployed on?
  - [ ] demo of what it takes to install it using deploygate (maybe make a video for us?)
- [ ] Any other comments on quality and extendability.

**Comment by arashbm** [comment]
I delivered my comments previously. We also decided to ditch deployGate and competitors in favour of app store.
