### ISSUE TITLE
Other apps/data sources

### ISSUE THREAD

**Issue by rkdarst** [CxAalto/koota-ios#2]
This issue has list of iOS applications that implement data collection frameworks.
- http://www.awareframework.com/
- https://github.com/OpenSensing/ios-opensensing
- https://github.com/nervousnet/nervousnet-iOS
  - https://itunes.apple.com/us/app/nervousnet/id1000599804?mt=8
  - http://www.nervousnet.ethz.ch/

To be moved to a wiki page here.  Wiki pages needed:
- Page with table of different apps, basic stats on them
  - What works now, what is planned, what is not possible with info.
- Page with each sensor/data source, info on it, and which apps can collect it.

**Comment by rkdarst** [comment]
- To be documented in koota-server wiki, not here.

**Comment by arashbm** [comment]
Closed as the discussion is already done.
