### ISSUE TITLE
Local data extraction? (low priority)

### ISSUE THREAD

**Issue by rkdarst** [CxAalto/koota-ios#8]
Idea: allow the app to be useful without a server.  Make a way for a user to extract the data and analyze it themselves.  This is low priority, but could make the app useful for others.  This should be done as quickly as possible, nothing fancy.

Considerations
- How to get off phone?
- Maximum data to store?
- UI?

**Comment by arashbm** [comment]
Users can access database (like any other apps) through their own iTunes logged in with the same account.
