### ISSUE TITLE
Supporting information for app store submission

### ISSUE THREAD

**Issue by rkdarst** [CxAalto/koota-ios#9]
- [ ] Icons:
  - [ ] High quality original
  - [ ] Scaling and bundling
- [ ] Description
- [ ] Screenshots

**Comment by arashbm** [comment]
@rkdarst I updated this with the metadata required for submission.

**Comment by rkdarst** [comment]
https://koota.cs.aalto.fi/static/norsu_detail.svg

Norsu - app logo.
